name: Sleep
main: fr.breakerland.sleep.Sleep
api-version: 1.13
version: 2.0
description: Skip the night !
authors: [LLIcocoman_Hrz, AzodFR]

commands:
  cancel:
    description: Cancel the skip!
    permission: sleep.cancel
permissions:
  sleep.cancel:
   default: true
   description: Allows to cancel skipping the night
  sleep.sleep:
   default: true
   description: Allows to skip
  sleep.*:
   description: Wildcard permission
   children:
     sleep.cancel: true
     sleep.sleep: true