name: BreakerLandSleep
main: fr.breakerland.breakerlandsleep.BreakerLandSleep
api-version: 1.13
version: 1.2
description: Skip the night !
authors: [LLIcocoman_Hrz, AzodFR]

commands:
  cancel:
    description: Cancel the skip!
    permission: breakerlandsleep.cancel
permissions:
  breakerlandsleep.cancel:
   default: true
   description: Allows to cancel skipping the night
  breakerlandsleep.sleep:
   default: true
   description: Allows to skip
  breakerlandsleep.*:
   description: Wildcard permission
   children:
     breakerlandsleep.cancel: true
     breakerlandsleep.sleep: true